<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Generate-data" data-toc-modified-id="Generate-data-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Generate data</a></span><ul class="toc-item"><li><span><a href="#Create-database" data-toc-modified-id="Create-database-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Create database</a></span></li><li><span><a href="#Query-database" data-toc-modified-id="Query-database-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Query database</a></span></li></ul></li></ul></div>

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [97]:
from collections import Counter

In [102]:
def is_anagram(a,b):
    return list(filter(lambda x: Counter(a) == Counter(x), b))

In [104]:
is_anagram('aha',['haa','aaa','aah','hola'])

['haa', 'aah']

In [ ]:
![img](https://images2.programmersought.com/354/33/33f0add3c13b3b2e5504f05e488b20ba.png)

![](https://images2.programmersought.com/354/33/33f0add3c13b3b2e5504f05e488b20ba.png)

In [67]:
a = np.random.randint(10, size=(3,3))
a

array([[1, 0, 2],
       [9, 0, 6],
       [2, 4, 2]])

In [93]:
def snail(array):
    return list(array[0]) + snail(np.array(list(zip(*array[1:])))[::-1]) if array.size else []

In [96]:
snail(a)

[1, 0, 2, 6, 2, 4, 2, 9, 0]

# Generate data 

In [34]:
users = pd.DataFrame({'id': np.arange(10000,20000),
 'first_order_id': np.arange(0,10000),
 'registration_date': [fake.date_between(start_date='-1y', end_date='today') for i in np.arange(0,10000)]
})
users

id  first_order_id registration_date
0     10000               0        2020-12-26
1     10001               1        2021-06-24
2     10002               2        2021-03-20
3     10003               3        2021-05-10
4     10004               4        2021-04-18
...     ...             ...               ...
9995  19995            9995        2021-01-08
9996  19996            9996        2020-09-13
9997  19997            9997        2020-10-13
9998  19998            9998        2021-05-09
9999  19999            9999        2020-10-01

[10000 rows x 3 columns]

In [40]:
order_points = pd.concat([pd.DataFrame({
 'order_id': orders.id,
 'point_type': ['DELIVERY'] * len(orders),
 'latitude': np.random.uniform(low=42.804419701589396, high=42.8269595840283, size=(len(users),)),                   
 'longitude' : np.random.uniform(low=-1.6220578023901806, high=-1.669350510044231, size=(len(users),))                      
}),pd.DataFrame({
 'order_id': orders.id,
 'point_type': ['PICKUP'] * len(orders),
 'latitude': np.random.uniform(low=42.804419701589396, high=42.8269595840283, size=(len(users),)),                   
 'longitude' : np.random.uniform(low=-1.6220578023901806, high=-1.669350510044231, size=(len(users),))                      
})])
           
order_points

order_id point_type   latitude  longitude
0            0   DELIVERY  42.810330  -1.663741
1            1   DELIVERY  42.806788  -1.658021
2            2   DELIVERY  42.816817  -1.665900
3            3   DELIVERY  42.824209  -1.662587
4            4   DELIVERY  42.814868  -1.627160
...        ...        ...        ...        ...
9995      9995     PICKUP  42.812906  -1.629015
9996      9996     PICKUP  42.817068  -1.631902
9997      9997     PICKUP  42.826432  -1.632565
9998      9998     PICKUP  42.815195  -1.653794
9999      9999     PICKUP  42.810642  -1.629944

[20000 rows x 4 columns]

In [38]:
orders = pd.DataFrame({'id': users.first_order_id,
 'customer_id': users.id,
 'activation_time_local': users.registration_date.apply(lambda x: fake.date_between(start_date=x,  end_date='+1M')),
 'courier_id': np.random.randint(100,200,len(users)),
 'acceptance_latitude': np.random.uniform(low=42.804419701589396, high=42.8269595840283, size=(len(users),)),                   
 'acceptance_longitude' : np.random.uniform(low=-1.6220578023901806, high=-1.669350510044231, size=(len(users),))                      
})
orders

id  customer_id activation_time_local  courier_id  \
0        0        10000            2021-03-04         112   
1        1        10001            2021-06-25         115   
2        2        10002            2021-07-27         114   
3        3        10003            2021-05-26         125   
4        4        10004            2021-06-13         160   
...    ...          ...                   ...         ...   
9995  9995        19995            2021-07-12         187   
9996  9996        19996            2020-11-09         112   
9997  9997        19997            2021-02-14         147   
9998  9998        19998            2021-05-21         122   
9999  9999        19999            2020-11-11         155   

      acceptance_latitude  acceptance_longitude  
0               42.810964             -1.645933  
1               42.807842             -1.655276  
2               42.812382             -1.664263  
3               42.806644             -1.667666  
4               42.810513             -1.665485  
...                   ...                   ...  
9995            42.811985             -1.634736  
9996            42.807340             -1.652087  
9997            42.818220             -1.645438  
9998            42.821605             -1.634958  
9999            42.819635             -1.648189  

[10000 rows x 6 columns]

In [6]:
np.random.randint(100,200,10)

array([128, 107, 112, 161, 179, 101, 113, 120, 107, 165])

In [ ]:
np.random.randint(100,200,10)

In [15]:
np.random.rand()

0.6791096317878984

In [16]:
np.random.uniform(low=42.804419701589396, high=42.8269595840283, size=(50,))

array([42.82547896, 42.80962144, 42.82167917, 42.8051713 , 42.8190304 ,
       42.8227647 , 42.80723901, 42.80648006, 42.80618437, 42.81592107,
       42.81606263, 42.81605636, 42.81341543, 42.81009735, 42.80527286,
       42.81805648, 42.8170884 , 42.82610331, 42.81507845, 42.8217145 ,
       42.8257491 , 42.80620268, 42.81881578, 42.81671143, 42.81810273,
       42.80722783, 42.81053384, 42.81901482, 42.81855328, 42.80824344,
       42.8046241 , 42.81009766, 42.80618176, 42.80653473, 42.81784155,
       42.80965406, 42.81762627, 42.82346602, 42.82645792, 42.80541973,
       42.82627607, 42.81944866, 42.80774046, 42.82051093, 42.81109388,
       42.8087905 , 42.81489207, 42.81321151, 42.81688083, 42.81613622])

In [18]:
np.random.uniform(low=-1.6220578023901806, high=-1.669350510044231, size=(50,))

array([-1.62860119, -1.66341489, -1.66764081, -1.62486016, -1.66838431,
       -1.64670876, -1.63466466, -1.63476525, -1.62517807, -1.65510791,
       -1.62503171, -1.64034542, -1.64058263, -1.62839078, -1.65212431,
       -1.63863851, -1.66850373, -1.6661375 , -1.63768025, -1.62386502,
       -1.65500897, -1.64870988, -1.63270967, -1.64473426, -1.66198474,
       -1.65391968, -1.62977625, -1.66808233, -1.64044378, -1.63055004,
       -1.66296478, -1.64278045, -1.63736357, -1.66455652, -1.66890379,
       -1.65550047, -1.65340948, -1.63691244, -1.65130797, -1.63203373,
       -1.6662076 , -1.64542561, -1.65733689, -1.64187883, -1.64373322,
       -1.66163076, -1.66526013, -1.62264178, -1.64203298, -1.64592813])

In [ ]:
42.8269595840283, -1.669350510044231

In [ ]:
42.804419701589396, -1.6220578023901806

In [19]:
import random

In [21]:
help(random.choice)

Help on method choice in module random:

choice(seq) method of random.Random instance
    Choose a random element from a non-empty sequence.



In [23]:
np.random.choice(['DELIVERY', 'PICKUP'], size=10)

array(['PICKUP', 'PICKUP', 'DELIVERY', 'DELIVERY', 'PICKUP', 'DELIVERY',
       'DELIVERY', 'DELIVERY', 'DELIVERY', 'PICKUP'], dtype='<U8')

In [25]:
!pip install faker

     |████████████████████████████████| 1.2 MB 2.0 MB/s eta 0:00:01
  Using cached text_unidecode-1.3-py2.py3-none-any.whl (78 kB)


In [27]:
from faker import Faker
fake = Faker()

fake.date_between(start_date='today', end_date='+30d')

datetime.date(2021, 8, 1)

In [58]:
cities = {
    'ES': ['BCN', 'MAD'],
    'UK': ['LON','MAN']
}

In [53]:
random.choice(['BCN', 'MAD'])

'BCN'

In [54]:
def get_city(country_code):
    return random.choice(cities[country_code])

In [55]:
events = pd.DataFrame({
 'creation_time': [fake.date_between(start_date='-1y',  end_date='today') for i in range(10000)],
 'country_code': np.random.choice(['ES','UK'], size=10000),                   
})
events

creation_time country_code
0       2021-04-29           ES
1       2020-09-20           UK
2       2020-07-15           UK
3       2020-09-11           UK
4       2021-06-06           UK
...            ...          ...
9995    2021-06-21           ES
9996    2020-09-19           UK
9997    2021-02-19           ES
9998    2021-01-03           UK
9999    2021-04-08           UK

[10000 rows x 2 columns]

In [71]:
events['city_code'] = events.country_code.apply(get_city)

In [72]:
events['stores_ids'] = events.country_code.apply(lambda x: random.sample(stores_ids, 100))

In [78]:
events.apply(lambda x: {'country_code': x['country_code'], 'city_code': x['city_code'], 'stores_ids':x['stores_ids'] }, axis=1)

0       {'country_code': 'ES', 'city_code': 'BCN', 'st...
1       {'country_code': 'UK', 'city_code': 'LON', 'st...
2       {'country_code': 'UK', 'city_code': 'LON', 'st...
3       {'country_code': 'UK', 'city_code': 'LON', 'st...
4       {'country_code': 'UK', 'city_code': 'MAN', 'st...
                              ...                        
9995    {'country_code': 'ES', 'city_code': 'BCN', 'st...
9996    {'country_code': 'UK', 'city_code': 'LON', 'st...
9997    {'country_code': 'ES', 'city_code': 'MAD', 'st...
9998    {'country_code': 'UK', 'city_code': 'LON', 'st...
9999    {'country_code': 'UK', 'city_code': 'LON', 'st...
Length: 10000, dtype: object

In [79]:
events['attributes_json'] = events.apply(lambda x: {'country_code': x['country_code'], 'city_code': x['city_code'], 'stores_ids':x['stores_ids'] }, axis=1)

In [81]:
events.reset_index()

index creation_time country_code city_code  \
0         0    2021-04-29           ES       BCN   
1         1    2020-09-20           UK       LON   
2         2    2020-07-15           UK       LON   
3         3    2020-09-11           UK       LON   
4         4    2021-06-06           UK       MAN   
...     ...           ...          ...       ...   
9995   9995    2021-06-21           ES       BCN   
9996   9996    2020-09-19           UK       LON   
9997   9997    2021-02-19           ES       MAD   
9998   9998    2021-01-03           UK       LON   
9999   9999    2021-04-08           UK       LON   

                                             stores_ids  \
0     [59, 51, 7, 40, 74, 68, 16, 33, 21, 72, 96, 12...   
1     [66, 53, 12, 15, 83, 7, 0, 68, 71, 96, 70, 67,...   
2     [89, 44, 80, 30, 16, 62, 21, 18, 13, 64, 29, 2...   
3     [51, 31, 71, 38, 99, 17, 30, 49, 75, 94, 63, 3...   
4     [97, 85, 56, 30, 46, 44, 71, 58, 1, 41, 16, 65...   
...                                                 ...   
9995  [8, 84, 0, 71, 26, 17, 28, 50, 32, 96, 18, 57,...   
9996  [24, 37, 95, 59, 31, 33, 89, 28, 3, 92, 8, 45,...   
9997  [2, 14, 37, 65, 72, 59, 47, 64, 86, 13, 90, 48...   
9998  [7, 20, 62, 50, 84, 12, 24, 14, 86, 10, 45, 82...   
9999  [15, 21, 0, 53, 88, 89, 87, 77, 72, 76, 8, 94,...   

                                        attributes_json  
0     {'country_code': 'ES', 'city_code': 'BCN', 'st...  
1     {'country_code': 'UK', 'city_code': 'LON', 'st...  
2     {'country_code': 'UK', 'city_code': 'LON', 'st...  
3     {'country_code': 'UK', 'city_code': 'LON', 'st...  
4     {'country_code': 'UK', 'city_code': 'MAN', 'st...  
...                                                 ...  
9995  {'country_code': 'ES', 'city_code': 'BCN', 'st...  
9996  {'country_code': 'UK', 'city_code': 'LON', 'st...  
9997  {'country_code': 'ES', 'city_code': 'MAD', 'st...  
9998  {'country_code': 'UK', 'city_code': 'LON', 'st...  
9999  {'country_code': 'UK', 'city_code': 'LON', 'st...  

[10000 rows x 6 columns]

## Create database

In [85]:
import sqlalchemy

In [45]:
sql_url = 'sqlite:///glovo.db'

In [47]:
users.to_sql('users', sql_url)
orders.to_sql('orders', sql_url)
order_points.to_sql('order_points', sql_url)
events[['creation_time', 'attributes_json']].to_sql('events', sql_url, dtype={'attributes_json': sqlalchemy.types.JSON}, if_exists='replace')

## Query database

In [3]:
%load_ext sql

In [4]:
%sql sqlite:///glovo.db

In [5]:
%%sql
SELECT *
FROM sqlite_master
WHERE type='table'
ORDER BY name;

 * sqlite:///glovo.db
Done.


[('table', 'events', 'events', 486, 'CREATE TABLE events (\n\t"index" BIGINT, \n\tcreation_time DATE, \n\tattributes_json JSON\n)'),
 ('table', 'order_points', 'order_points', 147, 'CREATE TABLE order_points (\n\t"index" BIGINT, \n\torder_id BIGINT, \n\tpoint_type TEXT, \n\tlatitude FLOAT, \n\tlongitude FLOAT\n)'),
 ('table', 'orders', 'orders', 2, 'CREATE TABLE orders (\n\t"index" BIGINT, \n\tid BIGINT, \n\tcustomer_id BIGINT, \n\tactivation_time_local DATE, \n\tcourier_id BIGINT, \n\tacceptance_latitude FLOAT, \n\tacceptance_longitude FLOAT\n)'),
 ('table', 'users', 'users', 392, 'CREATE TABLE users (\n\t"index" BIGINT, \n\tid BIGINT, \n\tfirst_order_id BIGINT, \n\tregistration_date DATE\n)')]

In [6]:
%%sql
select *
from users 
limit 10;

 * sqlite:///glovo.db
Done.


[(0, 10000, 0, '2020-12-26'),
 (1, 10001, 1, '2021-06-24'),
 (2, 10002, 2, '2021-03-20'),
 (3, 10003, 3, '2021-05-10'),
 (4, 10004, 4, '2021-04-18'),
 (5, 10005, 5, '2021-03-26'),
 (6, 10006, 6, '2021-07-03'),
 (7, 10007, 7, '2021-06-12'),
 (8, 10008, 8, '2020-12-13'),
 (9, 10009, 9, '2021-07-10')]

In [59]:
%%sql
with ops as
(select strftime('%Y-%m',creation_time) as month, 
json_extract(attributes_json, '$.country_code') as country_code,
json_extract(attributes_json, '$.city_code') as city_code,
json_extract(attributes_json, '$.stores_ids') as restaurants
from events),
restaurants as(
    select *
    from ops cross join json_each(ops.restaurants)
)
select month, country_code, value as restaurant, avg(key) as position
from restaurants
group by value, country_code, month
order by position
limit 10

 * sqlite:///glovo.db
Done.


[('2020-07', 'UK', 46, 43.18402777777778),
 ('2021-07', 'UK', 11, 44.046783625730995),
 ('2021-01', 'UK', 14, 44.85749385749386),
 ('2020-07', 'UK', 94, 44.979166666666664),
 ('2020-12', 'UK', 6, 45.0994623655914),
 ('2021-07', 'ES', 10, 45.14754098360656),
 ('2020-07', 'ES', 61, 45.149825783972126),
 ('2021-03', 'ES', 96, 45.20235294117647),
 ('2020-08', 'UK', 51, 45.31127450980392),
 ('2020-10', 'ES', 79, 45.37649880095923)]

In [30]:
%%sql
with fechas as
(select users.id as user_id, 
  registration_date, 
  activation_time_local first_order_date, 
  strftime('%Y', registration_date) reg_y, 
  strftime('%W', registration_date) reg_w,
  strftime('%Y', activation_time_local) first_y, 
  strftime('%W', activation_time_local) first_w
from users inner join orders on users.first_order_id = orders.id)
select reg_y,reg_w,
  case when reg_y = first_y then first_w -reg_w else 1 end as n_weeks, count(*) as num
from fechas
group by reg_y,reg_w,
  case when reg_y = first_y then first_w -reg_w else 1 end
order by  reg_y,reg_w, n_weeks
limit 30

 * sqlite:///glovo.db
Done.


[('2020', '27', 1, 21),
 ('2020', '27', 5, 2),
 ('2020', '27', 6, 1),
 ('2020', '27', 7, 1),
 ('2020', '27', 12, 1),
 ('2020', '27', 19, 2),
 ('2020', '27', 20, 1),
 ('2020', '28', 0, 2),
 ('2020', '28', 1, 118),
 ('2020', '28', 2, 5),
 ('2020', '28', 3, 5),
 ('2020', '28', 4, 3),
 ('2020', '28', 6, 3),
 ('2020', '28', 7, 2),
 ('2020', '28', 9, 3),
 ('2020', '28', 10, 5),
 ('2020', '28', 11, 4),
 ('2020', '28', 12, 2),
 ('2020', '28', 13, 6),
 ('2020', '28', 14, 1),
 ('2020', '28', 16, 2),
 ('2020', '28', 17, 4),
 ('2020', '28', 18, 7),
 ('2020', '28', 19, 2),
 ('2020', '28', 20, 3),
 ('2020', '28', 21, 4),
 ('2020', '28', 22, 2),
 ('2020', '28', 23, 1),
 ('2020', '28', 24, 7),
 ('2020', '29', 0, 1)]

In [11]:
%%sql
with order_locations as
(select order_id,
sum(case when point_type = 'DELIVERY' then latitude end) as delivery_latitude,
sum(case when point_type = 'PICKUP' then latitude end) as pickup_latitude,
sum(case when point_type = 'DELIVERY' then longitude end) as delivery_longitude,
sum(case when point_type = 'PICKUP' then longitude end) as pickup_longitude
from order_points
group by order_id)
select o.id, sqrt(pow(acceptance_latitude - pickup_latitude,2) + pow(acceptance_longitude - pickup_longitude,2)) as pickup_distance,
sqrt(pow(delivery_latitude - pickup_latitude,2) + pow(delivery_longitude - pickup_longitude,2)) as delivery_distance
from orders o inner join order_locations p on p.order_id = o.id
limit 10

 * sqlite:///glovo.db
Done.


[(0, 0.02281087056055513, 0.04025315059454986),
 (1, 0.015595566555587456, 0.015114367300566376),
 (2, 0.027100663149330306, 0.030028001498727194),
 (3, 0.01717774856431793, 0.0015161342811099252),
 (4, 0.027733370184139187, 0.010853266398571065),
 (5, 0.013913684494746822, 0.032123148731159866),
 (6, 0.008926647666995026, 0.012425454472648416),
 (7, 0.04345347631799838, 0.01071665472953692),
 (8, 0.010766821540085457, 0.03094654434725825),
 (9, 0.03246394293608333, 0.03676898759761316)]

In [22]:
%%sql
select o.id, sqrt(pow(acceptance_latitude - latitude,2) + pow(acceptance_longitude - longitude,2)) as distance
from orders o inner join order_points p on p.order_id = o.id
limit 10

 * sqlite:///glovo.db
Done.


[(0, 0.02281087056055513),
 (0, 0.01781972158058553),
 (1, 0.0029401797954782998),
 (1, 0.015595566555587456),
 (2, 0.027100663149330306),
 (2, 0.004727781178394607),
 (3, 0.01717774856431793),
 (3, 0.01828479621467412),
 (4, 0.027733370184139187),
 (4, 0.03857206112975395)]

In [20]:
%%sql
SELECT strftime('%Y', date('now')), strftime('%W', date('now')) week, rank() partition ;

 * sqlite:///glovo.db
Done.


[('2021', '28')]

In [ ]:
%%sql
select *
from 

In [18]:
%%sql 
select pow(4,2) from users limit 1

 * sqlite:///glovo.db
Done.


[(16.0,)]

In [3]:
import sqlite3

In [4]:
sqlite3.version

'2.6.0'

In [5]:
sqlite3.sqlite_version

'3.36.0'